### ISSUE TITLE
App not detecting gamedig

### ISSUE THREAD

**Issue by sewziom** [RatWasHere/bmods#17]
After I installed gamedig in my cmd: 
![image](https://github.com/RatWasHere/bmods/assets/99766623/e3ff0b9d-d097-491d-a53f-6b242e1cd338)
It shows  that it works
But when I run a command with a mod that requires gamedig it shows this error
![image](https://github.com/RatWasHere/bmods/assets/99766623/b6f2c36f-de56-4324-b8da-25fafff7273b)
This means that gamedig is not installed, but after i checked it is installed.
Please help

**Comment by RatWasHere** [comment]
you have to install gamedig in the apps install folder
